WIP Spawndata refactor
Mooses2k/SecretHistories pull request #682
Opened 2024-09-20 20:16 UTC by eh-jogos

Fixes Issue #612 

## SpawnData Refactor
Changes are made mostly inline with the comment in that issue.
SpawnData was refactored to be more of a base class, and any other type of spawn can extend it with its own specifications. Right now we have:
```
- SpawnData 
|- CharacterSpawnData (used for NPCs)
|- ItemSpawnData
  |- SarcophagusSpawnData
```

## LargeObjectSpawn was removed and refactored into AnchorSpawner. 

It expects to be configured on the editor with a nodepath to a node that has several Marker3D as before.
But now it doesn't  need the owner to have specific variables and doesn't decide the position on where to spawn the items that were decided in the world generation phase. Instead it just expects someone else to give it a dictionary of index of Marker3D nodes as keys and SpawnData as values and chooses the correct nodes by index and uses the SpawnData to spawn there.

The sarcophagus itself receives that dictionary from it's spawn data, and uses the AnchorSpawner spawn them.

All of the decision making logic is in the world generation phases, using the correct rng, and all of the spawning logic itself is in the spawn data.

## Astar during world generation
Some other improvements were made, now after corridors are generated we update the Astar to be a representation of walkable cells. This can be used in following steps, for example, I'm using it for spawning items from the initial settings "debug" list close to the player. 

After spawning sarcos close to walls, I'm also removing the wall tiles from the Astar, as you can walk on the "second" tile the sarco width occupies but not close to the wall where the bulk of the sarco is located. Center sarcos are rare and they might be occupying a large area of two tiles if they're centralized so I couldn't find a good way to do it should be possible in the future if this is desired or necessary.

Here is how the visualization of the Astar looks like (red outlined tiles are the Astar Grid, yellow lines are the Astar connections)
![image](https://github.com/user-attachments/assets/9a1512bd-4813-4670-88f6-f8d80a268bdc)

This can be shown/hidden or configured in the RoomGraphViz scene.

2024-11-12 02:53 UTC, Mooses2k requested changes
1) triviality: typo in C:\Games\GODOT\SecretHistories\utils\debug_scenes_base\game_placholder.gd (should be game_placeholder.gd)
2) You left a debug light around the player active
3) Mostly a note for me, I will have to check why the wall with a grate near the floor is still screwed up z-fighting in your branch.
Mooses2k — Today at 6:42 PM
4) Repeatable crash entering DLvl 5 on seeds -30069 and 0. 
Out of bounds get index '5' (on base: 'Dictionary') on line 450 of world_data.gd
Remember, < and > are debug DLvl change keys.
5) Please merge dev4, I'm guessing it's a trivial thing from inventory.gd of Visnicio's PR I just merged. Comments only affected, I think. 
6) Not a problem, just a thanks. I'm happy with how you did the debug start menu spawning of initial items, that's so much better, thanks.
That's it. The rest of my testing didn't find problems. This will be very nice to have in the game once 1, 2, 4, 5 are done.

2024-12-19 18:46 UTC, Mooses2k commented
@eh-jogos Just checking in here - only a few things left.

> 1. triviality: typo in C:\Games\GODOT\SecretHistories\utils\debug_scenes_base\game_placholder.gd (should be game_placeholder.gd)
> 2. You left a debug light around the player active
> 3. nm, fixed
> 4. Repeatable crash entering DLvl 5 on seeds -30069 and 0.
>    Out of bounds get index '5' (on base: 'Dictionary') on line 450 of world_data.gd
>    Remember, < and > are debug DLvl change keys.
> 5. Please merge dev4, I'm guessing it's a trivial thing from inventory.gd of Visnicio's PR I just merged. Comments only affected, I think.
> 
> Thanks. I'm happy with how you did the debug start menu spawning of initial items, that's so much better, thanks.
> 
> That's it. The rest of my testing didn't find problems. This will be very nice to have in the game once 1, 2, 4, 5 are done.

2025-03-17 18:39 UTC, Mooses2k approved these changes
Fixed and ready to merge.

2025-07-18 17:43 UTC, Visnicio commented
Fixed small conflict after the character audio refactor, merging now

2025-07-18 17:43 UTC, merged