Fencing sim level design
Mooses2k/SecretHistories pull request #708
Opened 2024-11-29 00:43 UTC by Visnicio

This PR intends to add the base for the level design and stuff needed for the fencing sim demo

2025-02-15 23:10 UTC, Visnicio commented
Oh also, ImGui was implemented via GDExtension to make easier the creation of runtime debug menus

2025-03-20 23:13 UTC, Visnicio commented
This PR closes these related items:

closes #693 #690

2025-07-21 22:25 UTC, Visnicio commented
Pending merge from `newcharacter-origin`

2025-07-27 02:29 UTC, Mooses2k requested changes
1) Put invisible walls on edges of fencing sim map
2) Replace player following light with a spotlight attached to the ceiling (above , shining down through) which moves), ensuring appropriate brightness across the five heights it will be at
3) Start with the ceiling lower, 2/3 the height maybe
4) Scarecrow nearer
5) First circle of candles smaller (as is now is about how it should be on floor 4 or 5)
6) Ceiling hole too circular, make it more jagged

2025-07-30 02:49 UTC, closed without merging